<?php
/**
 * Builds the installable SQL files from PHP definitions:
 *   install/seed.sql         core data every store needs (roles, settings, pages, shipping, gateways, homepage)
 *   install/sample-data.sql  demo catalogue (categories, products, variants, images, collections, slides…)
 *   install/database.sql     schema + seed + sample data in ONE file for phpMyAdmin import
 *
 * Usage: php tools/build-sample-data.php
 */
if (PHP_SAPI !== 'cli') {
    exit('CLI only');
}
$root = dirname(__DIR__);

function q($v): string
{
    if ($v === null) {
        return 'NULL';
    }
    if (is_bool($v)) {
        return $v ? '1' : '0';
    }
    if (is_int($v) || is_float($v)) {
        return (string) $v;
    }
    if (is_array($v)) {
        $v = json_encode($v, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }
    return "'" . str_replace(["\\", "'", "\n", "\r"], ["\\\\", "\\'", "\\n", "\\r"], (string) $v) . "'";
}

function ins(string $table, array $rows): string
{
    if (!$rows) {
        return '';
    }
    $cols = array_keys($rows[0]);
    $sql = "INSERT INTO `$table` (`" . implode('`,`', $cols) . "`) VALUES\n";
    $vals = [];
    foreach ($rows as $r) {
        $vals[] = '(' . implode(',', array_map('q', array_values($r))) . ')';
    }
    return $sql . implode(",\n", $vals) . ";\n\n";
}

// =========================================================== CORE SEED
$seed = "-- Beglet core seed data (generated by tools/build-sample-data.php)\nSET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS = 0;\n\n";

$permissions = [
    ['dashboard.view', 'View dashboard', 'Dashboard'],
    ['products.view', 'View products', 'Catalogue'], ['products.edit', 'Create & edit products', 'Catalogue'], ['products.delete', 'Delete products', 'Catalogue'],
    ['products.cost_price', 'View & edit cost prices', 'Catalogue'], ['categories.manage', 'Manage categories', 'Catalogue'],
    ['collections.manage', 'Manage collections', 'Catalogue'], ['inventory.manage', 'Manage inventory', 'Catalogue'], ['reviews.manage', 'Moderate reviews', 'Catalogue'],
    ['orders.view', 'View orders', 'Sales'], ['orders.edit', 'Update orders & fulfilment', 'Sales'], ['orders.refund', 'Record refunds & COD collection', 'Sales'],
    ['orders.export', 'Export orders', 'Sales'], ['coupons.manage', 'Manage coupons', 'Sales'],
    ['customers.view', 'View customers', 'Customers'], ['customers.edit', 'Edit customers', 'Customers'], ['newsletter.manage', 'Manage newsletter', 'Customers'], ['messages.view', 'Read contact messages', 'Customers'],
    ['content.homepage', 'Homepage builder', 'Content'], ['content.slides', 'Hero slides', 'Content'], ['content.pages', 'Pages', 'Content'], ['content.testimonials', 'Testimonials', 'Content'],
    ['shipping.manage', 'Shipping & delivery', 'Settings'], ['payments.manage', 'Payment gateways & transactions', 'Settings'],
    ['settings.general', 'General settings', 'Settings'], ['settings.theme', 'Theme settings', 'Settings'], ['seo.manage', 'SEO tools', 'Settings'],
    ['admins.manage', 'Manage administrators & roles', 'System'], ['audit.view', 'View audit log', 'System'],
];
$permRows = [];
foreach ($permissions as $i => [$key, $label, $group]) {
    $permRows[] = ['id' => $i + 1, 'perm_key' => $key, 'label' => $label, 'group_name' => $group];
}
$permId = array_flip(array_column($permRows, 'perm_key'));
$roles = [
    [1, 'Super Admin', 'super_admin', 'Full control over the website, including administrators, payments and system settings.', array_keys($permId)],
    [2, 'Store Manager', 'store_manager', 'Products, categories, inventory, orders and customers.', ['dashboard.view', 'products.view', 'products.edit', 'products.delete', 'products.cost_price', 'categories.manage', 'collections.manage', 'inventory.manage', 'reviews.manage', 'orders.view', 'orders.edit', 'orders.refund', 'orders.export', 'coupons.manage', 'customers.view', 'customers.edit', 'messages.view']],
    [3, 'Order Manager', 'order_manager', 'Order processing and fulfilment.', ['dashboard.view', 'orders.view', 'orders.edit', 'orders.refund', 'orders.export', 'customers.view', 'messages.view', 'products.view']],
    [4, 'Content Manager', 'content_manager', 'Banners, homepage sections and informational pages.', ['dashboard.view', 'content.homepage', 'content.slides', 'content.pages', 'content.testimonials', 'collections.manage', 'reviews.manage', 'products.view']],
];
$seed .= ins('admin_permissions', $permRows);
$seed .= ins('admin_roles', array_map(fn($r) => ['id' => $r[0], 'name' => $r[1], 'slug' => $r[2], 'description' => $r[3], 'is_system' => 1], $roles));
$rp = [];
foreach ($roles as $r) {
    foreach ($r[4] as $k) {
        $rp[] = ['role_id' => $r[0], 'permission_id' => $permId[$k] + 1];
    }
}
$seed .= ins('admin_role_permissions', $rp);
$seed .= "-- Default administrator. Password: ChangeMe@2026 (you will be forced to change it on first login)\n";
$seed .= ins('admins', [['id' => 1, 'role_id' => 1, 'name' => 'Store Owner', 'email' => 'admin@example.com', 'password_hash' => password_hash('ChangeMe@2026', PASSWORD_DEFAULT), 'status' => 'active', 'must_change_password' => 1]]);

$care = "<p>Wipe clean with a soft, dry cloth. Keep away from prolonged moisture, direct sunlight and heat. Condition occasionally with a leather care product suited to the finish, testing on a hidden area first.</p>";
$settings = [
    // general
    ['site_name', 'Beglet', 'general'], ['brand_name', 'Beglet', 'general'], ['site_tagline', 'Crafted Leather', 'general'],
    ['browser_title', 'Beglet — Premium Crafted Leather Wallets & Accessories', 'general'],
    ['seo_default_description', 'Beglet designs refined leather wallets, card holders and everyday carry accessories — timeless essentials built for daily use.', 'seo'],
    ['contact_phone', '+92 300 0000000', 'general'], ['whatsapp_number', '923000000000', 'general'], ['support_email', 'care@example.com', 'general'],
    ['notification_email', 'orders@example.com', 'general'], ['business_address', "Studio address\nCity, Pakistan", 'general'], ['business_hours', 'Mon–Sat, 10:00–19:00', 'general'],
    ['social_instagram', 'https://www.instagram.com/', 'general'], ['social_facebook', 'https://www.facebook.com/', 'general'], ['social_tiktok', '', 'general'],
    ['social_youtube', '', 'general'], ['social_pinterest', '', 'general'], ['social_x', '', 'general'],
    ['currency_code', 'PKR', 'general'], ['currency_symbol', 'Rs.', 'general'], ['currency_position', 'before', 'general'], ['currency_decimals', '0', 'general'],
    ['timezone', 'Asia/Karachi', 'general'], ['date_format', 'd M Y', 'general'], ['time_format', 'h:i A', 'general'], ['default_language', 'en', 'general'],
    ['maintenance_mode', '0', 'general'], ['maintenance_message', 'We are refining a few details. Please check back shortly.', 'general'],
    ['logo_path', '', 'general'], ['favicon_path', 'assets/img/brand/favicon.svg', 'general'],
    ['footer_about', 'Refined leather essentials designed for everyday carry — considered details, enduring style.', 'general'],
    ['copyright_text', 'Beglet. All rights reserved.', 'general'], ['store_country', 'Pakistan', 'general'], ['order_prefix', 'BG', 'general'],
    ['products_per_page', '12', 'general'], ['wishlist_enabled', '1', 'general'], ['reviews_enabled', '1', 'general'], ['recently_viewed_enabled', '1', 'general'],
    ['email_enabled', '1', 'general'], ['email_status_updates', '1', 'general'], ['newsletter_welcome_email', '1', 'general'], ['low_stock_email', '1', 'general'],
    ['checkout_require_terms', '1', 'general'], ['unpaid_order_timeout_hours', '2', 'general'], ['show_sample_content', '1', 'general'],
    ['popular_searches', 'bifold, card holder, travel, key fob', 'general'],
    ['mega_menu_image', 'assets/img/sample/misc/mega-menu.jpg', 'general'], ['mega_menu_link', '/shop', 'general'], ['mega_menu_caption', 'Shop the collection', 'general'],
    ['main_menu', [['label' => 'Shop', 'url' => '/shop', 'mega' => true], ['label' => 'New Arrivals', 'url' => '/shop?sort=newest'], ['label' => 'The Noir Edit', 'url' => '/collection/the-noir-edit'], ['label' => 'Our Story', 'url' => '/about-us'], ['label' => 'Contact', 'url' => '/contact']], 'general'],
    ['announcement_enabled', '1', 'general'],
    ['announcement_messages', [['text' => 'Free delivery on orders over Rs. 5,000', 'url' => '/shop'], ['text' => 'Cash on delivery available nationwide', 'url' => ''], ['text' => 'Gift packaging available on selected pieces', 'url' => '/shop']], 'general'],
    ['announcement_bg', '#0A1426', 'general'], ['announcement_color', '#E8DDCC', 'general'], ['announcement_interval', '5000', 'general'],
    ['pdp_delivery_text', 'Dispatched within 1–2 working days', 'general'], ['pdp_returns_text', 'Easy returns — see our returns policy', 'general'],
    ['pdp_shipping_returns', "We deliver across Pakistan. Delivery charges and estimated delivery times are shown at checkout before you place your order.\n\nIf something is not right, you can request a return in line with our Returns Policy. Items should be unused and in their original packaging.", 'general'],
    ['whatsapp_float', '1', 'general'], ['whatsapp_message', 'Hello Beglet, I have a question.', 'general'],
    ['contact_intro', 'Questions about a product or an order? We usually reply within one working day.', 'general'],
    ['shop_heading', 'Shop All', 'general'], ['shop_intro', 'Wallets, card holders and everyday accessories — designed to be carried daily and kept for years.', 'general'],
    ['shop_seo_title', 'Shop Leather Wallets, Card Holders & Accessories', 'seo'], ['shop_meta_description', 'Browse the full Beglet collection of leather wallets, card holders, travel wallets and accessories.', 'seo'],
    ['home_seo_title', '', 'seo'], ['home_meta_description', 'Beglet designs refined leather wallets, card holders and everyday carry accessories — timeless essentials built for daily use.', 'seo'],
    // shipping
    ['shipping_default_rate', '250', 'shipping'], ['shipping_default_estimate', '3–5 working days', 'shipping'], ['free_shipping_enabled', '1', 'shipping'],
    ['free_shipping_threshold', '5000', 'shipping'], ['minimum_order_amount', '0', 'shipping'], ['express_enabled', '1', 'shipping'], ['checkout_regions', '', 'shipping'],
    // seo
    ['seo_title_template', '{title} | {site}', 'seo'], ['seo_indexing_enabled', '1', 'seo'], ['robots_txt', '', 'seo'], ['ads_txt', '', 'seo'],
    ['google_site_verification', '', 'seo'], ['bing_site_verification', '', 'seo'], ['ga4_measurement_id', '', 'seo'], ['head_scripts', '', 'seo'], ['body_scripts', '', 'seo'],
    ['og_default_image', 'assets/img/brand/og-default.jpg', 'seo'], ['twitter_handle', '', 'seo'],
];
$theme = [
    'theme_primary' => '#214E9B', 'theme_secondary' => '#101D35', 'theme_dark' => '#0A1426', 'theme_ivory' => '#F7F5F0', 'theme_beige' => '#E8DDCC',
    'theme_accent' => '#B99A5B', 'theme_header_bg' => '#101D35', 'theme_header_text' => '#F7F5F0', 'theme_footer_bg' => '#0A1426', 'theme_footer_text' => '#E8DDCC',
    'theme_button_bg' => '#214E9B', 'theme_button_text' => '#FFFFFF', 'theme_body_bg' => '#F7F5F0', 'theme_text' => '#1B2333', 'theme_fonts' => 'cormorant_inter',
    'theme_base_font_size' => '16', 'theme_container' => '1320', 'theme_section_spacing' => '96', 'theme_radius' => '4', 'theme_card_style' => 'classic',
    'theme_header_layout' => 'logo_left', 'theme_footer_layout' => 'columns', 'theme_mobile_columns' => '2', 'theme_mobile_sticky_cart' => '1', 'theme_animations' => '1',
];
foreach ($theme as $k => $v) {
    $settings[] = [$k, $v, 'theme'];
}
$seed .= ins('site_settings', array_map(fn($s) => ['setting_key' => $s[0], 'setting_value' => is_array($s[1]) ? json_encode($s[1], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) : $s[1], 'setting_group' => $s[2]], $settings));

$seed .= ins('payment_gateways', [
    ['code' => 'cod', 'display_name' => 'Cash on Delivery', 'description' => 'Pay in cash when your order arrives.', 'is_enabled' => 1, 'mode' => 'live', 'config' => json_encode(['fee' => '0', 'max_order_amount' => '0', 'instructions' => 'Please keep the exact amount ready for the courier.']), 'sort_order' => 1],
    ['code' => 'easypaisa', 'display_name' => 'Easypaisa', 'description' => 'Pay with your Easypaisa mobile account.', 'is_enabled' => 0, 'mode' => 'sandbox', 'config' => json_encode(new stdClass()), 'sort_order' => 2],
    ['code' => 'jazzcash', 'display_name' => 'JazzCash', 'description' => 'Pay with your JazzCash mobile account.', 'is_enabled' => 0, 'mode' => 'sandbox', 'config' => json_encode(new stdClass()), 'sort_order' => 3],
    ['code' => 'card', 'display_name' => 'Debit / Credit Card', 'description' => 'Visa & Mastercard via a secure hosted payment page.', 'is_enabled' => 0, 'mode' => 'sandbox', 'config' => json_encode(['provider' => 'jazzcash']), 'sort_order' => 4],
]);

$seed .= ins('shipping_zones', [
    ['id' => 1, 'name' => 'Karachi', 'is_default' => 0, 'cod_available' => 1, 'is_active' => 1, 'sort_order' => 1],
    ['id' => 2, 'name' => 'Lahore', 'is_default' => 0, 'cod_available' => 1, 'is_active' => 1, 'sort_order' => 2],
    ['id' => 3, 'name' => 'Islamabad & Rawalpindi', 'is_default' => 0, 'cod_available' => 1, 'is_active' => 1, 'sort_order' => 3],
    ['id' => 4, 'name' => 'Rest of Pakistan', 'is_default' => 1, 'cod_available' => 1, 'is_active' => 1, 'sort_order' => 9],
]);
$seed .= ins('shipping_zone_locations', [
    ['zone_id' => 1, 'city' => 'Karachi', 'region' => 'Sindh'],
    ['zone_id' => 2, 'city' => 'Lahore', 'region' => 'Punjab'],
    ['zone_id' => 3, 'city' => 'Islamabad', 'region' => 'Islamabad Capital Territory'],
    ['zone_id' => 3, 'city' => 'Rawalpindi', 'region' => 'Punjab'],
]);
$seed .= ins('shipping_rates', [
    ['zone_id' => 1, 'method' => 'standard', 'name' => 'Standard delivery', 'rate' => 200, 'free_over' => null, 'min_days' => 1, 'max_days' => 3, 'is_active' => 1],
    ['zone_id' => 1, 'method' => 'express', 'name' => 'Express (next working day)', 'rate' => 450, 'free_over' => null, 'min_days' => 1, 'max_days' => 1, 'is_active' => 1],
    ['zone_id' => 2, 'method' => 'standard', 'name' => 'Standard delivery', 'rate' => 200, 'free_over' => null, 'min_days' => 1, 'max_days' => 3, 'is_active' => 1],
    ['zone_id' => 2, 'method' => 'express', 'name' => 'Express (next working day)', 'rate' => 450, 'free_over' => null, 'min_days' => 1, 'max_days' => 1, 'is_active' => 1],
    ['zone_id' => 3, 'method' => 'standard', 'name' => 'Standard delivery', 'rate' => 220, 'free_over' => null, 'min_days' => 2, 'max_days' => 4, 'is_active' => 1],
    ['zone_id' => 3, 'method' => 'express', 'name' => 'Express', 'rate' => 500, 'free_over' => null, 'min_days' => 1, 'max_days' => 2, 'is_active' => 1],
    ['zone_id' => 4, 'method' => 'standard', 'name' => 'Standard delivery', 'rate' => 300, 'free_over' => null, 'min_days' => 3, 'max_days' => 6, 'is_active' => 1],
]);

$pages = [
    ['About Us', 'about-us', 'company', "<h2>Crafted to be carried</h2><p>Beglet began with a simple idea: the things you carry every day should be made with care, look better with age and never get in your way.</p><p>We design wallets, card holders and small leather goods with clean lines, considered proportions and practical layouts. Every detail — from the spacing of a card slot to the finish of an edge — is chosen to make daily use effortless.</p><h3>What we believe</h3><ul><li><strong>Fewer, better things.</strong> Pieces designed to be used daily for years.</li><li><strong>Honest materials.</strong> We describe our materials accurately on every product page.</li><li><strong>Service that cares.</strong> Real people answering your questions.</li></ul><p><em>Store owner: please review and personalise this page, adding only claims about materials, production and origin that you can substantiate.</em></p>"],
    ['Shipping Policy', 'shipping-policy', 'service', "<h2>Delivery across Pakistan</h2><p>Delivery charges and estimated delivery times for your city are calculated and shown at checkout before you place your order.</p><ul><li>Orders are usually dispatched within 1–2 working days.</li><li>Standard and, where available, express options are offered at checkout.</li><li>Free standard delivery applies to orders above the threshold shown on our website.</li></ul><p>You will receive tracking details by email once your order ships. You can also check your order status anytime on our <a href=\"/track-order\">order tracking page</a>.</p>"],
    ['Returns & Exchanges', 'returns-policy', 'service', "<h2>Returns</h2><p>If you are not satisfied with your purchase, please contact us within 7 days of delivery to arrange a return or exchange.</p><ul><li>Items must be unused, in original condition and packaging.</li><li>Personalised items and gift cards cannot be returned unless faulty.</li><li>Refunds are issued to the original payment method once the return is received and inspected. Cash on delivery orders are refunded by bank transfer or mobile wallet.</li></ul><p><em>Store owner: adjust the return window and conditions to match your actual policy.</em></p>"],
    ['FAQ', 'faq', 'service', "<h3>Do you offer cash on delivery?</h3><p>Yes — cash on delivery is available across most of Pakistan. Availability and any applicable fee are shown at checkout.</p><h3>Do I need an account to order?</h3><p>No. You can check out as a guest and track your order using your order number and email address.</p><h3>How do I care for my wallet?</h3><p>Wipe with a soft dry cloth and keep away from prolonged moisture and heat. Specific care guidance is listed on each product page.</p>"],
    ['Privacy Policy', 'privacy-policy', 'policy', "<h2>Your privacy</h2><p>We collect the information needed to process your orders and provide customer service: your name, contact details, delivery address and order history.</p><h3>How we use your data</h3><ul><li>To fulfil and deliver orders and to contact you about them.</li><li>To send marketing emails only if you have opted in — you can unsubscribe at any time via the link in every email.</li><li>To keep our website secure and prevent fraud.</li></ul><h3>Payments</h3><p>Online payments are processed on our payment providers' secure pages. We never receive or store your card number, CVV or wallet PIN.</p><h3>Your rights</h3><p>You may request access to, correction of or deletion of your personal data by contacting us.</p><p><em>Store owner: have this policy reviewed to make sure it reflects your actual practices and applicable law.</em></p>"],
    ['Terms & Conditions', 'terms-and-conditions', 'policy', "<h2>Terms of sale</h2><p>By placing an order you agree to these terms. Prices are shown in Pakistani Rupees and include applicable taxes unless stated otherwise.</p><ul><li>Orders are subject to availability and confirmation.</li><li>We reserve the right to cancel orders in case of pricing errors or suspected fraud; any payment taken will be refunded in full.</li><li>Product colours may vary slightly from images due to screen settings.</li></ul><p><em>Store owner: review these terms with a legal adviser before launch.</em></p>"],
];
$seed .= ins('pages', array_map(fn($p, $i) => ['title' => $p[0], 'slug' => $p[1], 'footer_group' => $p[2], 'content' => $p[3], 'sort_order' => $i, 'is_published' => 1, 'seo_title' => null, 'meta_description' => null, 'noindex' => 0], $pages, array_keys($pages)));

// Homepage sections
$sections = [
    ['hero', 'hero', 'Hero carousel', ['autoplay' => '1', 'interval' => '6500', 'transition' => 'fade', 'transition_speed' => '1400', 'show_arrows' => '1', 'show_dots' => '1', 'ken_burns' => '1']],
    ['categories', 'categories', 'Shop by category', ['eyebrow' => 'The collection', 'title' => 'Shop by Category', 'subtitle' => 'Six families of everyday essentials, each designed around how you actually carry.', 'source' => 'flagged', 'limit' => '6', 'layout' => 'mosaic']],
    ['new_arrivals', 'new_arrivals', 'New arrivals', ['eyebrow' => 'Just in', 'title' => 'New Arrivals', 'subtitle' => 'The latest additions to the Beglet collection.', 'source' => 'flagged', 'count' => '8', 'cta_label' => 'Shop new arrivals', 'cta_url' => '/shop?sort=newest']],
    ['brand_story', 'brand_story', 'Brand story', ['eyebrow' => 'Crafted to last', 'title' => 'Made with patience. Designed for years.', 'body' => "Every Beglet piece starts with a question: how will this be used, every single day? We obsess over the small things — the depth of a card slot, the weight of a fold, the way an edge feels in your hand.\n\nThe result is a collection of quiet, considered essentials that become more personal the longer you carry them.", 'image' => 'assets/img/sample/story/materials.jpg', 'image_alt' => 'A fan of leather swatches in cognac, espresso, oxblood, tan, navy and black', 'secondary_image' => 'assets/img/sample/story/stitch-detail.jpg', 'secondary_alt' => 'Close-up of contrast stitching on a cognac wallet', 'image_position' => 'left', 'parallax' => '1', 'button_label' => 'Discover our story', 'button_url' => '/about-us', 'bg_color' => '']],
    ['best_sellers', 'best_sellers', 'Best sellers', ['eyebrow' => 'Most loved', 'title' => 'Best Sellers', 'subtitle' => 'The pieces our customers return to again and again.', 'source' => 'auto', 'count' => '8', 'cta_label' => 'Shop best sellers', 'cta_url' => '/shop?sort=popular', 'bg_color' => '#101D35', 'text_theme' => 'light']],
    ['featured_collection', 'featured_collection', 'Featured collection', ['eyebrow' => 'Limited edit', 'title' => 'The Noir Edit', 'description' => 'Black pebbled leather finished with antique-gold stitching. A study in understatement.', 'source_type' => 'collection', 'collection_id' => '1', 'image' => 'assets/img/sample/misc/collection-noir.jpg', 'image_alt' => 'Black leather wallets with gold stitching on a navy background', 'layout' => 'split_left', 'product_count' => '4', 'button_label' => 'Explore The Noir Edit']],
    ['benefits', 'benefits', 'Craftsmanship & benefits', ['eyebrow' => 'The Beglet standard', 'title' => 'Considered in every detail', 'subtitle' => '', 'bg_color' => '', 'items' => [
        ['icon' => 'gem', 'title' => 'Selected leathers', 'text' => 'Each material is chosen for how it feels, wears and ages.'],
        ['icon' => 'scissors', 'title' => 'Careful construction', 'text' => 'Precise cutting, even stitching and finished edges.'],
        ['icon' => 'grid-3x3-gap', 'title' => 'Everyday function', 'text' => 'Layouts designed around how you really carry.'],
        ['icon' => 'gift', 'title' => 'Gift-ready packaging', 'text' => 'Optional presentation packaging on selected pieces.'],
        ['icon' => 'headset', 'title' => 'Caring support', 'text' => 'Real people on WhatsApp, phone and email.'],
    ]]],
    ['testimonials', 'testimonials', 'Testimonials', ['eyebrow' => 'Kind words', 'title' => 'From our customers', 'show_rating' => '1', 'limit' => '6']],
    ['newsletter', 'newsletter', 'Newsletter', ['title' => 'Join the Beglet circle', 'text' => 'New collections, care guides and private offers — never more than twice a month.', 'consent_text' => 'I agree to receive marketing emails from Beglet. I can unsubscribe at any time.', 'button_label' => 'Subscribe', 'image' => 'assets/img/sample/misc/leather-texture.jpg']],
];
$seed .= ins('homepage_sections', array_map(fn($s, $i) => ['section_key' => $s[0], 'section_type' => $s[1], 'label' => $s[2], 'is_enabled' => 1, 'sort_order' => ($i + 1) * 10, 'settings' => json_encode($s[3], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES), 'draft_settings' => null], $sections, array_keys($sections)));
$seed .= "SET FOREIGN_KEY_CHECKS = 1;\n";

// =========================================================== SAMPLE DATA
$catalogue = require __DIR__ . '/sample-catalogue.php';
$sample = "-- Beglet demo catalogue (generated by tools/build-sample-data.php)\n-- Images are procedurally rendered placeholders in assets/img/sample — replace with real photography.\nSET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS = 0;\n\n";
$cats = [
    [1, null, 'Bifold Wallets', 'bifold-wallets', 'The timeless fold — card slots, note compartments and a slim profile.', 1],
    [2, null, 'Minimalist Wallets', 'minimalist-wallets', 'Slim designs for those who carry only what matters.', 2],
    [3, null, 'Card Holders', 'card-holders', 'Compact holders for cards and folded notes.', 3],
    [4, null, 'Long Wallets', 'long-wallets', 'Generous long wallets that keep notes flat and cards organised.', 4],
    [5, null, 'Travel Wallets', 'travel-wallets', 'Passport covers and organisers for the journey.', 5],
    [6, null, 'Leather Accessories', 'leather-accessories', 'Key holders, pouches and finishing touches.', 6],
    [7, 1, 'Classic Bifold', 'classic-bifold', 'Traditional bifolds with multiple card slots.', 1],
    [8, 1, 'Coin Pocket Bifold', 'coin-pocket-bifold', 'Bifolds with a dedicated coin pocket.', 2],
    [9, 2, 'Slim Wallets', 'slim-wallets', 'Ultra-thin wallets for the front pocket.', 1],
    [10, 6, 'Key Holders', 'key-holders', 'Leather key fobs and organisers.', 1],
    [11, 6, 'Pouches', 'pouches', 'Coin and earphone pouches.', 2],
];
$catRows = [];
$catId = [];
foreach ($cats as [$id, $parent, $name, $slug, $short, $sort]) {
    $catId[$slug] = $id;
    $top = $parent === null;
    $catRows[] = [
        'id' => $id, 'parent_id' => $parent, 'name' => $name, 'slug' => $slug, 'short_description' => $short,
        'description' => '<p>' . $short . ' Explore the ' . strtolower($name) . ' collection from Beglet — designed for everyday carry with considered details.</p>',
        'image' => $top ? "assets/img/sample/categories/$slug.jpg" : null,
        'banner_image' => $top ? "assets/img/sample/categories/$slug-banner.jpg" : null,
        'image_alt' => $name, 'seo_title' => $name . ' — Leather ' . ($top ? 'Collection' : 'Wallets'), 'meta_description' => $short,
        'sort_order' => $sort, 'is_active' => 1, 'show_on_home' => $top ? 1 : 0,
    ];
}
$sample .= ins('categories', $catRows);

$prodRows = $imgRows = $varRows = $valRows = $invRows = $movRows = [];
$imgId = 1;
$varId = 1;
$ago = 0;
foreach ($catalogue as $i => $p) {
    $pid = $i + 1;
    $catSlug = $p['cat'];
    $desc = '<p>' . $p['short'] . '</p><p>Designed by Beglet for daily use, the ' . $p['name'] . ' pairs a clean silhouette with a practical interior. Edges are finished for a refined feel and the stitching is kept tight and even for durability.</p><ul><li>Material: ' . $p['material'] . '</li><li>Finish: ' . $p['finish'] . '</li><li>Dimensions: approx. ' . $p['l'] . ' × ' . $p['w'] . ' mm</li></ul>';
    $prodRows[] = [
        'id' => $pid, 'category_id' => $catId[$catSlug], 'subcategory_id' => $p['sub'] ? $catId[$p['sub']] : null,
        'name' => $p['name'], 'slug' => $p['slug'], 'sku' => $p['sku'], 'short_description' => $p['short'], 'description' => $desc,
        'regular_price' => $p['price'], 'sale_price' => $p['sale'], 'cost_price' => round($p['price'] * 0.42),
        'track_stock' => 1, 'stock_status' => 'in_stock', 'low_stock_threshold' => 5,
        'is_featured' => in_array('featured', $p['flags'], true) ? 1 : 0, 'is_new_arrival' => in_array('new', $p['flags'], true) ? 1 : 0, 'is_best_seller' => in_array('best', $p['flags'], true) ? 1 : 0,
        'wallet_type' => $p['type'], 'material' => $p['material'], 'finish' => $p['finish'], 'care_instructions' => $care,
        'weight_grams' => $p['g'], 'length_mm' => $p['l'], 'width_mm' => $p['w'], 'height_mm' => $p['h'],
        'gift_wrap_available' => $p['gift'][0], 'gift_wrap_price' => $p['gift'][1], 'status' => 'published',
        'seo_title' => null, 'meta_description' => null, 'published_at' => date('Y-m-d H:i:s', strtotime('2026-09-01') + $i * 86400),
        'created_at' => date('Y-m-d H:i:s', strtotime('2026-09-01') + $i * 86400),
    ];
    // images: main colour gets 3 images, second colour 1 image
    $firstColourImageIds = [];
    foreach ([1, 2, 3] as $n) {
        $imgRows[] = ['id' => $imgId, 'product_id' => $pid, 'file_path' => "assets/img/sample/products/{$p['slug']}-$n.jpg", 'alt_text' => $p['name'] . ' in ' . strtolower($p['colors'][0]['name']) . ' — ' . ['', 'front view', 'angled view', 'stitching detail'][$n], 'caption' => null, 'is_main' => $n === 1 ? 1 : 0, 'sort_order' => $n];
        $firstColourImageIds[] = $imgId++;
    }
    $colourImage = [0 => $firstColourImageIds[0]];
    if (isset($p['colors'][1])) {
        $c = $p['colors'][1];
        $imgRows[] = ['id' => $imgId, 'product_id' => $pid, 'file_path' => "assets/img/sample/products/{$p['slug']}-{$c['key']}-1.jpg", 'alt_text' => $p['name'] . ' in ' . strtolower($c['name']), 'caption' => null, 'is_main' => 0, 'sort_order' => 4];
        $colourImage[1] = $imgId++;
    }
    foreach ($p['colors'] as $ci => $c) {
        $varRows[] = ['id' => $varId, 'product_id' => $pid, 'sku' => $p['sku'] . '-' . strtoupper(substr($c['key'], 0, 3)), 'label' => $c['name'], 'color_name' => $c['name'], 'color_hex' => $c['hex'], 'price_override' => null, 'sale_override' => null, 'image_id' => $colourImage[$ci] ?? null, 'sort_order' => $ci, 'is_active' => 1];
        $valRows[] = ['variant_id' => $varId, 'attribute_name' => 'Colour', 'attribute_value' => $c['name']];
        $qty = $p['stock'][$ci] ?? 10;
        $invRows[] = ['product_id' => $pid, 'variant_id' => $varId, 'quantity' => $qty];
        $movRows[] = ['product_id' => $pid, 'variant_id' => $varId, 'change_qty' => $qty, 'balance' => $qty, 'reason' => 'initial', 'note' => 'Sample data'];
        $varId++;
    }
}
$sample .= ins('products', $prodRows);
$sample .= ins('product_images', $imgRows);
$sample .= ins('product_variants', $varRows);
$sample .= ins('product_variant_values', $valRows);
$sample .= ins('product_inventory', $invRows);
$sample .= ins('inventory_movements', $movRows);

$slugToId = [];
foreach ($catalogue as $i => $p) {
    $slugToId[$p['slug']] = $i + 1;
}
$rel = [];
$relations = [
    'heritage-bifold-wallet' => ['related' => ['signature-coin-bifold', 'executive-bifold-wallet', 'midnight-noir-bifold'], 'cross_sell' => ['loop-key-fob', 'atelier-card-holder'], 'upsell' => ['continental-zip-wallet']],
    'slimline-minimalist-wallet' => ['related' => ['front-pocket-minimal-wallet', 'atelier-card-holder'], 'cross_sell' => ['loop-key-fob'], 'upsell' => ['heritage-bifold-wallet']],
    'atelier-card-holder' => ['related' => ['quick-draw-card-sleeve', 'noir-card-case'], 'cross_sell' => ['ridge-key-organizer', 'cove-coin-pouch'], 'upsell' => ['slimline-minimalist-wallet']],
    'voyager-passport-cover' => ['related' => ['nomad-travel-organizer'], 'cross_sell' => ['atelier-card-holder', 'loop-key-fob'], 'upsell' => ['nomad-travel-organizer']],
    'continental-zip-wallet' => ['related' => ['classic-long-wallet'], 'cross_sell' => ['cove-coin-pouch'], 'upsell' => []],
    'midnight-noir-bifold' => ['related' => ['noir-card-case', 'heritage-bifold-wallet'], 'cross_sell' => ['noir-card-case'], 'upsell' => []],
];
foreach ($relations as $src => $types) {
    foreach ($types as $type => $targets) {
        foreach ($targets as $k => $t) {
            $rel[] = ['product_id' => $slugToId[$src], 'related_id' => $slugToId[$t], 'relation_type' => $type, 'sort_order' => $k];
        }
    }
}
$sample .= ins('product_relations', $rel);

$sample .= ins('collections', [
    ['id' => 1, 'name' => 'The Noir Edit', 'slug' => 'the-noir-edit', 'description' => 'Black pebbled leather finished with antique-gold stitching. A study in understatement.', 'image' => 'assets/img/sample/misc/collection-noir.jpg', 'image_alt' => 'The Noir Edit', 'seo_title' => 'The Noir Edit — Black Leather Wallets', 'meta_description' => 'Black leather wallets and card cases with antique-gold stitching.', 'sort_order' => 1, 'is_active' => 1],
    ['id' => 2, 'name' => 'The Gift Edit', 'slug' => 'the-gift-edit', 'description' => 'Thoughtful pieces with optional gift packaging — for birthdays, Eid and every occasion.', 'image' => 'assets/img/sample/categories/leather-accessories.jpg', 'image_alt' => 'Gift edit', 'seo_title' => 'Leather Gifts', 'meta_description' => 'Leather wallet and accessory gift ideas with optional gift packaging.', 'sort_order' => 2, 'is_active' => 1],
]);
$cp = [];
foreach (['midnight-noir-bifold', 'noir-card-case', 'heritage-bifold-wallet', 'executive-bifold-wallet', 'continental-zip-wallet'] as $k => $s) {
    $cp[] = ['collection_id' => 1, 'product_id' => $slugToId[$s], 'sort_order' => $k];
}
foreach (['loop-key-fob', 'atelier-card-holder', 'cove-coin-pouch', 'heritage-bifold-wallet', 'voyager-passport-cover', 'slimline-minimalist-wallet'] as $k => $s) {
    $cp[] = ['collection_id' => 2, 'product_id' => $slugToId[$s], 'sort_order' => $k];
}
$sample .= ins('collection_products', $cp);

$sample .= ins('banner_slides', [
    ['title' => 'Crafted to be carried', 'subtitle' => 'The Autumn Collection', 'description' => 'Refined leather wallets and everyday essentials, designed for the way you move.', 'image_desktop' => 'assets/img/sample/hero/hero-1-desktop.jpg', 'image_mobile' => 'assets/img/sample/hero/hero-1-mobile.jpg', 'image_alt' => 'Cognac bifold, black card holder and tan key fob on a midnight blue surface', 'primary_btn_text' => 'Shop the collection', 'primary_btn_url' => '/shop', 'secondary_btn_text' => 'New arrivals', 'secondary_btn_url' => '/shop?sort=newest', 'text_align' => 'left', 'content_position' => 'middle', 'text_color' => '#F7F5F0', 'accent_color' => '#B99A5B', 'btn_bg_color' => '#214E9B', 'btn_text_color' => '#FFFFFF', 'overlay_color' => '#0A1426', 'overlay_opacity' => 30, 'height_desktop' => 760, 'height_mobile' => 640, 'bg_position' => 'center center', 'bg_size' => 'cover', 'sort_order' => 1, 'is_active' => 1],
    ['title' => 'Quiet luxury, every day', 'subtitle' => 'Long wallets & bifolds', 'description' => 'Clean lines, tight stitching and layouts that keep everything in its place.', 'image_desktop' => 'assets/img/sample/hero/hero-2-desktop.jpg', 'image_mobile' => 'assets/img/sample/hero/hero-2-mobile.jpg', 'image_alt' => 'Espresso long wallet, navy bifold and stone minimalist wallet on warm beige', 'primary_btn_text' => 'Explore wallets', 'primary_btn_url' => '/category/bifold-wallets', 'secondary_btn_text' => 'Long wallets', 'secondary_btn_url' => '/category/long-wallets', 'text_align' => 'left', 'content_position' => 'middle', 'text_color' => '#101D35', 'accent_color' => '#8A6A2E', 'btn_bg_color' => '#101D35', 'btn_text_color' => '#FFFFFF', 'overlay_color' => '#F7F5F0', 'overlay_opacity' => 10, 'height_desktop' => 760, 'height_mobile' => 640, 'bg_position' => 'center center', 'bg_size' => 'cover', 'sort_order' => 2, 'is_active' => 1],
    ['title' => 'Made for the journey', 'subtitle' => 'Travel wallets', 'description' => 'Passport covers and organisers that keep documents safe and close at hand.', 'image_desktop' => 'assets/img/sample/hero/hero-3-desktop.jpg', 'image_mobile' => 'assets/img/sample/hero/hero-3-mobile.jpg', 'image_alt' => 'Oxblood passport cover and tan coin pouch on navy', 'primary_btn_text' => 'Shop travel', 'primary_btn_url' => '/category/travel-wallets', 'secondary_btn_text' => null, 'secondary_btn_url' => null, 'text_align' => 'left', 'content_position' => 'middle', 'text_color' => '#F7F5F0', 'accent_color' => '#B99A5B', 'btn_bg_color' => '#B99A5B', 'btn_text_color' => '#0A1426', 'overlay_color' => '#0A1426', 'overlay_opacity' => 25, 'height_desktop' => 760, 'height_mobile' => 640, 'bg_position' => 'center center', 'bg_size' => 'cover', 'sort_order' => 3, 'is_active' => 1],
]);

$sample .= "-- SAMPLE testimonials: flagged is_sample = 1 and only shown while 'Show sample content' is on.\n-- Replace with genuine customer feedback before launch.\n";
$sample .= ins('testimonials', [
    ['author_name' => 'Sample Customer', 'author_meta' => 'Sample testimonial — replace', 'quote' => 'Replace this with genuine feedback from a real customer. Sample text shown for layout purposes only.', 'rating' => 5, 'is_sample' => 1, 'is_active' => 1, 'sort_order' => 1, 'source_note' => 'Demo content'],
    ['author_name' => 'Sample Customer', 'author_meta' => 'Sample testimonial — replace', 'quote' => 'Testimonials should be real quotes you have permission to publish, ideally linked to a verified order.', 'rating' => 5, 'is_sample' => 1, 'is_active' => 1, 'sort_order' => 2, 'source_note' => 'Demo content'],
]);
$sample .= ins('coupons', [
    ['code' => 'WELCOME10', 'description' => 'Sample: 10% off first order (max Rs. 1,000)', 'discount_type' => 'percent', 'discount_value' => 10, 'min_order_amount' => 3000, 'max_discount' => 1000, 'usage_limit' => null, 'per_customer_limit' => 1, 'is_active' => 1],
    ['code' => 'FREESHIP', 'description' => 'Sample: free delivery', 'discount_type' => 'free_shipping', 'discount_value' => 0, 'min_order_amount' => 0, 'max_discount' => null, 'usage_limit' => 100, 'per_customer_limit' => null, 'is_active' => 1],
]);
$sample .= "SET FOREIGN_KEY_CHECKS = 1;\n";

file_put_contents("$root/install/seed.sql", $seed);
file_put_contents("$root/install/sample-data.sql", $sample);
file_put_contents("$root/install/database.sql",
    "-- =====================================================================\n-- Beglet — complete install (schema + core seed + demo catalogue)\n-- Import this single file in phpMyAdmin. For a store without demo\n-- products, import schema.sql + seed.sql instead.\n-- =====================================================================\n\n"
    . file_get_contents("$root/install/schema.sql") . "\n" . $seed . "\n" . $sample);
echo "Wrote install/seed.sql, install/sample-data.sql, install/database.sql\n";
