<?php
/**
 * Demo catalogue definition — single source for the sample images and the
 * sample SQL (tools/build-sample-data.php). Product copy avoids claims the
 * merchant has not verified (leather grade, handmade, origin, warranty).
 */
$C = [
    'cognac' => ['key' => 'cognac', 'name' => 'Cognac', 'hex' => '#8B4A22'],
    'espresso' => ['key' => 'espresso', 'name' => 'Espresso', 'hex' => '#3B2418'],
    'black' => ['key' => 'black', 'name' => 'Black', 'hex' => '#1C1B1D'],
    'navy' => ['key' => 'navy', 'name' => 'Navy', 'hex' => '#1D2C4D'],
    'tan' => ['key' => 'tan', 'name' => 'Tan', 'hex' => '#A86A3D'],
    'oxblood' => ['key' => 'oxblood', 'name' => 'Oxblood', 'hex' => '#5A1F22'],
    'stone' => ['key' => 'stone', 'name' => 'Stone', 'hex' => '#8A7967'],
    'forest' => ['key' => 'forest', 'name' => 'Forest', 'hex' => '#2F3E30'],
];

return [
    ['slug' => 'heritage-bifold-wallet', 'name' => 'Heritage Bifold Wallet', 'sku' => 'BG-BF-001', 'cat' => 'bifold-wallets', 'sub' => 'classic-bifold', 'shape' => 'bifold', 'grain' => 'pebble', 'bg' => 'ivory',
     'price' => 6950, 'sale' => 5950, 'type' => 'Bifold', 'material' => 'Pebbled leather', 'finish' => 'Burnished edges', 'w' => 85, 'l' => 112, 'h' => 14, 'g' => 78,
     'flags' => ['featured', 'best', 'new'], 'gift' => [1, 350], 'colors' => [$C['cognac'], $C['espresso'], $C['black']], 'stock' => [24, 9, 3],
     'short' => 'A classic bifold with eight card slots, two note compartments and a slim profile that settles comfortably into a jacket or trouser pocket.',
    ],
    ['slug' => 'signature-coin-bifold', 'name' => 'Signature Coin Bifold', 'sku' => 'BG-BF-002', 'cat' => 'bifold-wallets', 'sub' => 'coin-pocket-bifold', 'shape' => 'bifold', 'grain' => 'smooth', 'bg' => 'beige',
     'price' => 7450, 'sale' => null, 'type' => 'Bifold', 'material' => 'Smooth leather', 'finish' => 'Matte', 'w' => 90, 'l' => 115, 'h' => 18, 'g' => 92,
     'flags' => ['best'], 'gift' => [1, 350], 'colors' => [$C['tan'], $C['navy']], 'stock' => [16, 11],
     'short' => 'Our bifold with a press-stud coin pocket — six card slots, a full-length note section and space for loose change.',
    ],
    ['slug' => 'executive-bifold-wallet', 'name' => 'Executive Bifold Wallet', 'sku' => 'BG-BF-003', 'cat' => 'bifold-wallets', 'sub' => 'classic-bifold', 'shape' => 'bifold_open', 'grain' => 'smooth', 'bg' => 'ivory',
     'price' => 8250, 'sale' => null, 'type' => 'Bifold', 'material' => 'Smooth leather', 'finish' => 'Polished', 'w' => 95, 'l' => 120, 'h' => 15, 'g' => 88,
     'flags' => ['featured'], 'gift' => [1, 350], 'colors' => [$C['espresso'], $C['black']], 'stock' => [12, 14],
     'short' => 'Twelve card slots, two hidden pockets and a structured spine designed to hold its shape for years of daily use.',
    ],
    ['slug' => 'slimline-minimalist-wallet', 'name' => 'Slimline Minimalist Wallet', 'sku' => 'BG-MN-001', 'cat' => 'minimalist-wallets', 'sub' => 'slim-wallets', 'shape' => 'minimalist', 'grain' => 'smooth', 'bg' => 'stone',
     'price' => 4450, 'sale' => null, 'type' => 'Minimalist', 'material' => 'Smooth leather', 'finish' => 'Natural', 'w' => 70, 'l' => 102, 'h' => 6, 'g' => 34,
     'flags' => ['new', 'best'], 'gift' => [1, 250], 'colors' => [$C['navy'], $C['stone'], $C['black']], 'stock' => [30, 18, 22],
     'short' => 'Just six millimetres thick: four card slots and a central pocket for folded notes. Everything you need, nothing you don\'t.',
    ],
    ['slug' => 'front-pocket-minimal-wallet', 'name' => 'Front Pocket Minimal Wallet', 'sku' => 'BG-MN-002', 'cat' => 'minimalist-wallets', 'sub' => 'slim-wallets', 'shape' => 'minimalist', 'grain' => 'pebble', 'bg' => 'ivory',
     'price' => 3950, 'sale' => 3450, 'type' => 'Minimalist', 'material' => 'Pebbled leather', 'finish' => 'Natural', 'w' => 68, 'l' => 100, 'h' => 7, 'g' => 30,
     'flags' => ['new'], 'gift' => [1, 250], 'colors' => [$C['black'], $C['cognac']], 'stock' => [20, 2],
     'short' => 'Designed for the front pocket — a quick-access thumb slot, three card pockets and a clean, rounded silhouette.',
    ],
    ['slug' => 'atelier-card-holder', 'name' => 'Atelier Card Holder', 'sku' => 'BG-CH-001', 'cat' => 'card-holders', 'sub' => null, 'shape' => 'cardholder', 'grain' => 'saffiano', 'bg' => 'beige',
     'price' => 2950, 'sale' => null, 'type' => 'Card holder', 'material' => 'Textured leather', 'finish' => 'Cross-grain', 'w' => 72, 'l' => 102, 'h' => 5, 'g' => 22,
     'flags' => ['featured', 'best'], 'gift' => [1, 250], 'colors' => [$C['oxblood'], $C['black'], $C['navy']], 'stock' => [26, 31, 0],
     'short' => 'Four exterior slots and a central pocket in a scratch-resistant cross-grain finish. A refined everyday essential.',
    ],
    ['slug' => 'quick-draw-card-sleeve', 'name' => 'Quick-Draw Card Sleeve', 'sku' => 'BG-CH-002', 'cat' => 'card-holders', 'sub' => null, 'shape' => 'cardholder', 'grain' => 'smooth', 'bg' => 'ivory',
     'price' => 2650, 'sale' => null, 'type' => 'Card holder', 'material' => 'Smooth leather', 'finish' => 'Satin', 'w' => 70, 'l' => 100, 'h' => 5, 'g' => 18,
     'flags' => ['new'], 'gift' => [0, 0], 'colors' => [$C['tan'], $C['forest']], 'stock' => [15, 13],
     'short' => 'A pull-tab sleeve that presents your most-used cards in a single motion, with two quick-access side slots.',
    ],
    ['slug' => 'noir-card-case', 'name' => 'Noir Card Case', 'sku' => 'BG-CH-003', 'cat' => 'card-holders', 'sub' => null, 'shape' => 'cardholder', 'grain' => 'pebble', 'bg' => 'stone',
     'price' => 3250, 'sale' => null, 'type' => 'Card holder', 'material' => 'Pebbled leather', 'finish' => 'Gold-tone stitching', 'w' => 72, 'l' => 102, 'h' => 6, 'g' => 24,
     'flags' => [], 'gift' => [1, 250], 'colors' => [$C['black']], 'stock' => [9], 'opt' => ['thread' => [185, 154, 91]],
     'short' => 'Black pebbled leather finished with contrast antique-gold stitching — part of The Noir Edit.',
    ],
    ['slug' => 'continental-zip-wallet', 'name' => 'Continental Zip Wallet', 'sku' => 'BG-LW-001', 'cat' => 'long-wallets', 'sub' => null, 'shape' => 'long', 'grain' => 'smooth', 'bg' => 'beige',
     'price' => 9950, 'sale' => null, 'type' => 'Long wallet', 'material' => 'Smooth leather', 'finish' => 'Polished, metal zip', 'w' => 100, 'l' => 195, 'h' => 25, 'g' => 165,
     'flags' => ['featured', 'new'], 'gift' => [1, 450], 'colors' => [$C['espresso'], $C['black']], 'stock' => [8, 6],
     'short' => 'A full zip-around long wallet with sixteen card slots, a zipped coin section and room for a phone.',
    ],
    ['slug' => 'classic-long-wallet', 'name' => 'Classic Long Wallet', 'sku' => 'BG-LW-002', 'cat' => 'long-wallets', 'sub' => null, 'shape' => 'long', 'grain' => 'pebble', 'bg' => 'ivory',
     'price' => 8950, 'sale' => 7950, 'type' => 'Long wallet', 'material' => 'Pebbled leather', 'finish' => 'Burnished edges', 'w' => 95, 'l' => 185, 'h' => 18, 'g' => 140,
     'flags' => ['best'], 'gift' => [1, 450], 'colors' => [$C['oxblood'], $C['navy']], 'stock' => [10, 7],
     'short' => 'An elegant long wallet that keeps notes flat and cards organised, ideal for a jacket breast pocket or bag.',
    ],
    ['slug' => 'voyager-passport-cover', 'name' => 'Voyager Passport Cover', 'sku' => 'BG-TW-001', 'cat' => 'travel-wallets', 'sub' => null, 'shape' => 'travel', 'grain' => 'pebble', 'bg' => 'beige',
     'price' => 5450, 'sale' => null, 'type' => 'Travel wallet', 'material' => 'Pebbled leather', 'finish' => 'Natural', 'w' => 100, 'l' => 140, 'h' => 10, 'g' => 82,
     'flags' => ['featured', 'new'], 'gift' => [1, 350], 'colors' => [$C['cognac'], $C['navy']], 'stock' => [14, 12],
     'short' => 'Protects your passport and keeps boarding passes, cards and a pen within reach — secured with an elastic band.',
    ],
    ['slug' => 'nomad-travel-organizer', 'name' => 'Nomad Travel Organizer', 'sku' => 'BG-TW-002', 'cat' => 'travel-wallets', 'sub' => null, 'shape' => 'travel', 'grain' => 'smooth', 'bg' => 'stone',
     'price' => 7950, 'sale' => null, 'type' => 'Travel wallet', 'material' => 'Smooth leather', 'finish' => 'Matte', 'w' => 115, 'l' => 220, 'h' => 20, 'g' => 190,
     'flags' => [], 'gift' => [1, 450], 'colors' => [$C['espresso'], $C['black']], 'stock' => [6, 4],
     'short' => 'A document organiser for longer trips: two passport sleeves, SIM card slots, a zip pocket and ticket compartment.',
    ],
    ['slug' => 'loop-key-fob', 'name' => 'Loop Key Fob', 'sku' => 'BG-AC-001', 'cat' => 'leather-accessories', 'sub' => 'key-holders', 'shape' => 'keyfob', 'grain' => 'smooth', 'bg' => 'ivory',
     'price' => 1850, 'sale' => null, 'type' => 'Key holder', 'material' => 'Smooth leather', 'finish' => 'Brass-tone ring', 'w' => 30, 'l' => 110, 'h' => 6, 'g' => 26,
     'flags' => ['best'], 'gift' => [1, 200], 'colors' => [$C['cognac'], $C['black'], $C['navy']], 'stock' => [40, 35, 28],
     'short' => 'A double-stitched leather loop with a solid split ring — a small luxury for everyday keys.',
    ],
    ['slug' => 'cove-coin-pouch', 'name' => 'Cove Coin Pouch', 'sku' => 'BG-AC-002', 'cat' => 'leather-accessories', 'sub' => 'pouches', 'shape' => 'coinpouch', 'grain' => 'smooth', 'bg' => 'beige',
     'price' => 2450, 'sale' => 2150, 'type' => 'Pouch', 'material' => 'Smooth leather', 'finish' => 'Press-stud closure', 'w' => 85, 'l' => 95, 'h' => 20, 'g' => 32,
     'flags' => ['new'], 'gift' => [1, 200], 'colors' => [$C['tan'], $C['oxblood']], 'stock' => [18, 15],
     'short' => 'A rounded coin and earphone pouch that opens wide, with a discreet press-stud closure.',
    ],
    ['slug' => 'ridge-key-organizer', 'name' => 'Ridge Key Organizer', 'sku' => 'BG-AC-003', 'cat' => 'leather-accessories', 'sub' => 'key-holders', 'shape' => 'keyfob', 'grain' => 'pebble', 'bg' => 'stone',
     'price' => 2250, 'sale' => null, 'type' => 'Key holder', 'material' => 'Pebbled leather', 'finish' => 'Gunmetal hardware', 'w' => 40, 'l' => 115, 'h' => 15, 'g' => 40,
     'flags' => [], 'gift' => [1, 200], 'colors' => [$C['espresso']], 'stock' => [12],
     'short' => 'Holds up to six keys silently folded inside a pebbled leather case — no more scratched phones.',
    ],
    ['slug' => 'midnight-noir-bifold', 'name' => 'Midnight Noir Bifold', 'sku' => 'BG-BF-004', 'cat' => 'bifold-wallets', 'sub' => 'classic-bifold', 'shape' => 'bifold', 'grain' => 'pebble', 'bg' => 'stone',
     'price' => 7250, 'sale' => null, 'type' => 'Bifold', 'material' => 'Pebbled leather', 'finish' => 'Gold-tone stitching', 'w' => 88, 'l' => 112, 'h' => 14, 'g' => 80,
     'flags' => ['featured'], 'gift' => [1, 350], 'colors' => [$C['black']], 'stock' => [0], 'opt' => ['thread' => [185, 154, 91]], 'preorder' => false,
     'short' => 'Black pebbled leather with antique-gold contrast stitching. The signature piece of The Noir Edit.',
    ],
];
